### Titanic dataset - examples on how to handle missing values depending on situation

This is a classic dataset in machine learning. It's also good practice on how to handle missing values without losing too much data.

In [171]:
# import modules
import numpy as np
import pandas as pd
import seaborn as sns

In [172]:
# load the dataset
df = sns.load_dataset("titanic")

In [173]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [174]:
# if we didn't pay attention, we would remove the NaN's straight away
df = df.dropna()

In [175]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [176]:
# since we just removed all data directly
# we just lost 80% of the data
182 / 891

0.20426487093153758

In [177]:
# re-load the dataset
df = sns.load_dataset("titanic")

In [178]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [179]:
# deck-column has 77% of values missing
# in this case it's just better to drop this column
# since it's beyond repair, basically
688 / 891

0.7721661054994389

In [180]:
# drop the column
df = df.drop("deck", axis=1)

In [181]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [182]:
# 20% of age is missing => let's attempt fixing this
177 / 891

0.19865319865319866

In [183]:
# the easy way => replace the missing age with average age
df['age'].mean()

np.float64(29.69911764705882)

In [184]:
# let's use groupby, WHAT IF we made a smarter imputation
# you can make this even fancier, for example:
# df.groupby(["class", "embark_town", "sex"]).mean(numeric_only=True)
# df.groupby(["class", "sex"]).mean(numeric_only=True)
# df.groupby("class").mean(numeric_only=True)

df.groupby("class").mean(numeric_only=True)

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
class,,,,,,,,
First,0.629630,1.0,38.233441,0.416667,0.356481,84.154687,0.550926,0.504630
Second,0.472826,2.0,29.877630,0.402174,0.380435,20.662183,0.538043,0.565217
Third,0.242363,3.0,25.140620,0.615071,0.393075,13.675550,0.649695,0.659878

In [185]:
# based on the price class and age:
# First class => ~ 38 years old
# Second class => ~ 30 years old
# Third class => 25 years old

# let's create a pandas function that fixes the missing age values
def impute_age(row):
    pclass = row['class']
    age = row['age']

    # the logic is this:
    # ONLY REPLACE THE AGE IF IT'S MISSING

    # IF THE AGE IS MISSING
    if pd.isnull(age):
        # fix the age based on price class
        if pclass == "First":
            return 38
        elif pclass == "Second":
            return 30
        else:
            return 25
    else:
        # use existing age, no need to change/impute
        return age

In [186]:
df.head(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,Queenstown,no,False
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,Southampton,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,Cherbourg,yes,True

In [187]:
df['age'] = df.apply(impute_age, axis=1)

In [188]:
df.head(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
5,0,3,male,25.0,0,0,8.4583,Q,Third,man,True,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,Queenstown,no,False
17,1,2,male,30.0,0,0,13.0000,S,Second,man,True,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,Southampton,no,False
19,1,3,female,25.0,0,0,7.2250,C,Third,woman,False,Cherbourg,yes,True

In [189]:
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [190]:
df = df.dropna()

In [191]:
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [192]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,25.0,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True