### Combining DataFrames, example 3 - more complex merge

In [33]:
import pandas as pd

products = [
    {"product_id": 11, "name": "SomeCorp CPU Accessory Kit 3", "price": 150},
    {"product_id": 12, "name": "WatIsDis Cooling Gear Collection 2024", "price": 250},
    {"product_id": 13, "name": "Generyc Processor f5-A12", "price": 350},
    {"product_id": 14, "name": "SemiPremium Processor f7-B33", "price": 449},
    {"product_id": 15, "name": "Ultimate Processor f9-C99", "price": 550}
]

orders = [
    {"product_id": 11, "delivery_time": 5, "delivery_method": "postal"},
    {"product_id": 11, "delivery_time": 3, "delivery_method": "courier"},
    {"product_id": 11, "delivery_time": 6, "delivery_method": "postal"},
    {"product_id": 12, "delivery_time": 7, "delivery_method": "postal"},
    {"product_id": 12, "delivery_time": 4, "delivery_method": "courier"},
    {"product_id": 12, "delivery_time": 8, "delivery_method": "postal"},
    {"product_id": 13, "delivery_time": 4, "delivery_method": "courier"},
    {"product_id": 13, "delivery_time": 6, "delivery_method": "postal"},
    {"product_id": 13, "delivery_time": 7, "delivery_method": "postal"},
    {"product_id": 14, "delivery_time": 8, "delivery_method": "postal"},
    {"product_id": 14, "delivery_time": 5, "delivery_method": "courier"},
    {"product_id": 14, "delivery_time": 6, "delivery_method": "postal"}
]

df1 = pd.DataFrame(products)
df2 = pd.DataFrame(orders)

In [34]:
df1

   product_id                                   name  price
0          11           SomeCorp CPU Accessory Kit 3    150
1          12  WatIsDis Cooling Gear Collection 2024    250
2          13               Generyc Processor f5-A12    350
3          14           SemiPremium Processor f7-B33    449
4          15              Ultimate Processor f9-C99    550

In [35]:
df2

    product_id  delivery_time delivery_method
0           11              5          postal
1           11              3         courier
2           11              6          postal
3           12              7          postal
4           12              4         courier
5           12              8          postal
6           13              4         courier
7           13              6          postal
8           13              7          postal
9           14              8          postal
10          14              5         courier
11          14              6          postal

### If we just merge the DataFrames like this, we'll mess up the data usually

... because there are more than one rows of data for each product in the second DataFrame.

In [36]:
df_new = df1.merge(df2, left_on="product_id", right_on="product_id", how="left")

In [37]:
df_new

,product_id,name,price,delivery_time,delivery_method
0,11,SomeCorp CPU Accessory Kit 3,150,5.0,postal
1,11,SomeCorp CPU Accessory Kit 3,150,3.0,courier
2,11,SomeCorp CPU Accessory Kit 3,150,6.0,postal
3,12,WatIsDis Cooling Gear Collection 2024,250,7.0,postal
4,12,WatIsDis Cooling Gear Collection 2024,250,4.0,courier
5,12,WatIsDis Cooling Gear Collection 2024,250,8.0,postal
6,13,Generyc Processor f5-A12,350,4.0,courier
7,13,Generyc Processor f5-A12,350,6.0,postal
8,13,Generyc Processor f5-A12,350,7.0,postal
9,14,SemiPremium Processor f7-B33,449,8.0,postal
10,14,SemiPremium Processor f7-B33,449,5.0,courier
11,14,SemiPremium Processor f7-B33,449,6.0,postal
12,15,Ultimate Processor f9-C99,550,NaN,NaN

In [ ]:
# in most cases, you don't want the amount of rows to increase
# after joining data!
print(f"Amount of data before joining: {len(df1)}")
print(f"Amount of data AFTER joining: {len(df_new)}")

Amount of data before joining: 5
Amount of data AFTER joining: 13

### Usually we have to reduce the amount of rows in the second DataFrame, so it matches the first one => use averages and groupby()

In [ ]:
# group the second DataFrame by averaging the delivery time
# for each product!
df2_grouped = df2.groupby("product_id").mean(numeric_only=True)

In [ ]:
# grouped average delivery times
df2_grouped

            delivery_time
product_id
11               4.666667
12               6.333333
13               5.666667
14               6.333333

In [ ]:
# merge with the grouped version of the second DataFrame
df_new = df1.merge(df2_grouped, left_on="product_id", right_on="product_id", how="left")

In [ ]:
# data amounts seem fine!
print(f"Amount of data before joining: {len(df1)}")
print(f"Amount of data AFTER joining: {len(df_new)}")

Amount of data before joining: 5
Amount of data AFTER joining: 5

In [ ]:
# merging looks OK, notice how one delivery time is NaN
# since the original df2 did not have any delivery times for product_id = 15
df_new

   product_id                                   name  price  delivery_time
0          11           SomeCorp CPU Accessory Kit 3    150       4.666667
1          12  WatIsDis Cooling Gear Collection 2024    250       6.333333
2          13               Generyc Processor f5-A12    350       5.666667
3          14           SemiPremium Processor f7-B33    449       6.333333
4          15              Ultimate Processor f9-C99    550            NaN