### Combining DataFrames, example 2 - simple merge

In [5]:
import pandas as pd

products = [
    {"product_id": 11, "name": "SomeCorp CPU Accessory Kit 3", "price": 150},
    {"product_id": 12, "name": "WatIsDis Cooling Gear Collection 2024", "price": 250},
    {"product_id": 13, "name": "Generyc Processor f5-A12", "price": 350},
    {"product_id": 14, "name": "SemiPremium Processor f7-B33", "price": 449},
    {"product_id": 15, "name": "Ultimate Processor f9-C99", "price": 550}
]

orders = [
    {"product_id": 11, "avg_delivery_time": 5},
    {"product_id": 12, "avg_delivery_time": 7},
    {"product_id": 13, "avg_delivery_time": 4},
    {"product_id": 14, "avg_delivery_time": 8},
    {"product_id": 15, "avg_delivery_time": 6}
]

df1 = pd.DataFrame(products)
df2 = pd.DataFrame(orders)

### The two DataFrames seems to have common column: product_id

**We can use this column to combine these DataFrames sideways.**

In [6]:
df1

   product_id                                   name  price
0          11           SomeCorp CPU Accessory Kit 3    150
1          12  WatIsDis Cooling Gear Collection 2024    250
2          13               Generyc Processor f5-A12    350
3          14           SemiPremium Processor f7-B33    449
4          15              Ultimate Processor f9-C99    550

In [7]:
df2

   product_id  avg_delivery_time
0          11                  5
1          12                  7
2          13                  4
3          14                  8
4          15                  6

In [8]:
# let's merge the df2 into df1
# common column product_id in both DataFrames
# USE LEFT JOIN
df1 = df1.merge(df2, left_on="product_id", right_on="product_id", how="left")

In [ ]:
# DataFrame merge seems fine!
df1

   product_id                                   name  price  avg_delivery_time
0          11           SomeCorp CPU Accessory Kit 3    150                  5
1          12  WatIsDis Cooling Gear Collection 2024    250                  7
2          13               Generyc Processor f5-A12    350                  4
3          14           SemiPremium Processor f7-B33    449                  8
4          15              Ultimate Processor f9-C99    550                  6