### Handling XML-data in pandas

In [42]:
import json
import numpy as np 
import pandas as pd 
import seaborn as sns

# in order to use XML-tools in pandas:
# pip install lxml

In [43]:
# pandas-way
df = pd.read_xml("somedata.xml")
df

   id     name  value
0  12  Testing  64521
1  31  Another  41572

In [44]:
# if the xml-data only has one piece of data (not a list of dictionaries)
# this no longer works
# df = pd.read_xml("somedata_single.xml")
# df

In [45]:
import xml.etree.ElementTree as et

# load XML-file -> get root node
xtree = et.parse("somedata_single.xml")
node = xtree.getroot()

# column names for pandas when we create the final DataFrame
df_cols = ["id", "name", "value"]
rows = []

# parse "columns" or values in the XML
e_id = node.find("id").text
e_name = node.find("name").text
e_value = node.find("value").text

# create the DataFrame
rows.append({'id': e_id, 'name': e_name, 'value': e_value})
out_df = pd.DataFrame(rows, columns=df_cols)

In [46]:
out_df

   id     name  value
0  12  Testing  64521

In [47]:
import pandas as pd
import xml.etree.ElementTree as et 
xtree = et.parse("somedata.xml")

# in this data, we have two nodes
nodes = xtree.getroot()
df_cols = ["id", "name", "value"]
rows = []

# loop through all item in array
for node in nodes:
    e_id = node.find("id").text
    e_name = node.find("name").text
    e_value = node.find("value").text

    rows.append({"id": e_id, "name": e_name, "value": e_value})
 
# create the DataFrame 
out_df = pd.DataFrame(rows, columns = df_cols)

In [48]:
out_df

   id     name  value
0  12  Testing  64521
1  31  Another  41572

In [49]:
# IF YOU CAN: TRY TO ALWAYS USE pd.read_xml() and the xpath-parameter
# in very very few cases, you might need to revert back to the traditional
df = pd.read_xml("somedata_single.xml", xpath="/*")
df

   id     name  value
0  12  Testing  64521

In [ ]:
# this is the default "xpath" in xml
# basically => data is the root node => use everything "*" inside data as an ITEM
df = pd.read_xml("somedata.xml", xpath="/data/*")
df

In [ ]:
# how xpath can be used to traverse your data, see:
# https://www.w3schools.com/xml/xpath_examples.asp